title:              Secret_Blog
email:              tmdqh04033@gmail.com
description:        CTF Contests writeup
author:             지승보
baseurl:            "/"
url:                "https://secretjuju.github.io"

# Social Profiles
github_username:    SecretJuJu
facebook_username:  지승보
instagram_username:  scret_juju

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
